baseURL = "/"
title = "Transportation GIS Projects"
author = "Amin Keramati"
copyright = "Â© 2020, Amin keramati"
paginate = 4
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "origin-hugo-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  description = "simple hugo theme"
  featured = true
  cssonly = false

  [params.socials]
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = ""
    medium= ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 10
    
 [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true


